### ISSUE TITLE
How to get d-vectors

### ISSUE THREAD

**Issue by Jamiroquai88** [FlorianKrey/DNC#2]
Hi, 
thank you for your work. 

I am trying to replicate your setup with AMI, but I have no idea, how to get d-vectors. You propose some augmentation technique, but when running those commands, it is trying to find arks I do not have. 

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/train/train.00.ark
```

I was able to download AMI (ihm) and process data, but I am not able to find anything on d-vectors.

Thanks.

**Comment by Jamiroquai88** [comment]
I am sorry, it looks like git refused to download data (arks) from `data/` directory.
I used 
```bash
git clone XY
```
is there some other command to download data?

Thanks.

**Comment by FlorianKrey** [comment]
Hi Jan,

thank you for your interest in our paper.
Did you go through the instructions in the README file of the repository?
The repository itself contains the "data/train/" folder with said file.
Those files contain the d-vectors used by us. If you want to use your own,
then you just need to create a d-vectors for each meeting and save them
in the kaldi-io format. Then (together with maybe some slight alterations)
you can use them with our code.

Feel free to ask any other questions.

Cheers,

Florian
________________________________

**Comment by FlorianKrey** [comment]
Oh I replied just as you messaged me again.
I see, the issue is that each ark file is too large
for your git settings (they are around 80MB I think).
You could use directly download them from the github
web-page through your webbrowser. You might also be
able to change your git settings. Just to be clear those
d-vectors are not AMI-data. They are processed AMI-data
forwarded through a neural network to create
speaker-embeddings.

________________________________

**Comment by Jamiroquai88** [comment]
Hi, thanks a lot for your response. I finally, understand, since I was not able to find d-vectors there, I thought that I need to generate them myself. Do you have some recipe, how to generate d-vectors that you are using? You are referencing a paper that is describing them, but I was not able to find a recipe to run.

**Comment by FlorianKrey** [comment]
https://arxiv.org/pdf/1902.03190.pdf
This is effectively the mode that we are using.
But any d-vector model trained with the angular softmax will work.
We trained our model with HTK. It might be easier for you to just
use PyTorch for all of this, you'd just need to save the embeddings
in the kaldi-io format to use the rest of the code.
________________________________

**Comment by Jamiroquai88** [comment]
Thanks. the network is training so closing this issue. It was pretty smooth with arks ;)
