### ISSUE TITLE
issues about training with init model

### ISSUE THREAD

**Issue by llior** [FlorianKrey/DNC#5]
Hi，
I tried to replicate the experiment，and follow yours step to train a DNC Transformer with the same configuration. The result of spectral cluster DER is the same，but the results of DNC are inconsistent. The DER of DNC is 32.52%，by contrast, the result of paper is 13.90%
My shell cmds are follow:
<details>
<summary>run.sh</summary>

```shell
#current path is DNC/
dnc_root=espnet/egs/ami/dnc1
path_to_datadir=data/augment_data
m50_real_augment_path=$path_to_datadir/m50.real.augment
m50_meeting_augment_path=$path_to_datadir/m50.meeting.augment
dvecdict_meeting_path=$path_to_datadir/dvecdict.meeting.split100
m50_real_path=$path_to_datadir/m50.real
SC_scoring_path=scoring/sys_rttm/SC_result
DNC_scoring_path=scoring/sys_rttm/DNC_result
data_path=data	
model_init=exp/mdm_train_pytorch_tag.for.model/results/model.acc.best
resume_path=exp/mdm_train_pytorch_tag.for.model/results/snapshot.ep.50

./path.sh
ln -s $dnc_root dnc1
#To generate training and validation data with sub-meeting length 50 and 1000 random shifts
python3 datapreperation/gen_augment_data.py --input-scps data/train.scp --input-mlfs data/train.mlf \
	--filtEncomp --maxlen 50 --augment 1000 --varnormalise $m50_real_augment_path
python3 datapreperation/gen_augment_data.py --input-scps data/dev.scp --input-mlfs data/dev.mlf \
	--filtEncomp --maxlen 50 --augment 1000 --varnormalise $m50_real_augment_path
	
#To generate training data with sub-meeting length 50 and 1000 random shifts using the meeting randomisation
python3 datapreperation/gen_dvecdict.py --input-scps data/train.scp --input-mlfs data/train.mlf \
	--filtEncomp --segLenConstraint 100 --meetingLevelDict $dvecdict_meeting_path
	
python3 datapreperation/gen_augment_data.py --input-scps data/train.scp --input-mlfs data/train.mlf \
	--filtEncomp --maxlen 50 --augment 100 --varnormalise --randomspeaker  \
	--dvectordict $dvecdict_meeting_path/train.npz $m50_meeting_augment_path
	
#To generate evaluation data
python3 datapreperation/gen_augment_data.py --input-scps data/eval.scp --input-mlfs data/eval.mlf \
	--filtEncomp --maxlen 50 --varnormalise $m50_real_path
	
cd $dnc_root

#To start training, run
CUDA_VISIBLE_DEVICES=1,2,3 ./run.sh --stage 4 --stop_stage 4 --train_json ../../../../$m50_real_augment_path/train.json \
	--ngpu 3 --dev_json ../../../../$m50_real_augment_path/dev.json --tag tag.for.model

#To track the progress of the training, run
tail -f exp/mdm_train_pytorch_tag.for.model/train.log

#Decode a DNC Tranformer
#Similar to the command used for training, run
#The decoding results are, by default, stored in multiple json files in exp/mdm_train_pytorch_tag.for.model/decode_dev_xxxxx/data.JOB.json
./run.sh --stage 5 --decode_json ../../../../$m50_real_path/eval.json --tag tag.for.model

cd ../../../../
#Running spectral clustering
#To run spectral clustering on previously generated evalutation data, for example for sub-meeting lengths 50:
python3 scoring/run_spectralclustering.py --p-percentile 0.95 --custom-dist cosine \
	--json-out $SC_scoring_path/eval95k24.1.json  $m50_real_path/eval.json
#Evaluation of clustering results
#First the DNC or SC output has to be converted into the RTTM format: 
#For SC:
python3 scoring/gen_rttm.py --input-scp $data_path/eval.scp --js-dir $SC_scoring_path \
	--js-num 1 --js-name eval95k24 --rttm-name eval95k24
#To score the result the reference rttm has to first be split into the appropriate sub-meeting lengths:
python3 scoring/split_rttm.py --submeeting-rttm $SC_scoring_path/eval95k24.rttm \
	--input-rttm scoring/refoutputeval.rttm --output-rttm $SC_scoring_path/reference.rttm
#Finally, the speaker error rate has to be calculated using:
python3 scoring/score_rttm.py --score-rttm $SC_scoring_path/eval95k24.rttm \
	--ref-rttm $SC_scoring_path/reference.rttm --output-scoredir $SC_scoring_path/result


#For DNC:
\cp $dnc_root/exp/mdm_train_pytorch_tag.for.model/decode_mdm_dev_decode/data* $DNC_scoring_path
python3 scoring/gen_rttm.py --input-scp $data_path/eval.scp --js-dir $DNC_scoring_path \
	--js-num 16 --js-name data --rttm-name evaldnc
#To score the result the reference rttm has to first be split into the appropriate sub-meeting lengths:
python3 scoring/split_rttm.py --submeeting-rttm $DNC_scoring_path/evaldnc.rttm \
	--input-rttm scoring/refoutputeval.rttm --output-rttm $DNC_scoring_path/reference.rttm
#Finally, the speaker error rate has to be calculated using:
python3 scoring/score_rttm.py --score-rttm $DNC_scoring_path/evaldnc.rttm \
	--ref-rttm $DNC_scoring_path/reference.rttm --output-scoredir $DNC_scoring_path/result
```
</details>

I consider the problem is that the training dataset was augmented by three ways, while I only used m50_real_augment dataset to train model. 
Then I want to add parameter --init_model $model_init to train m50_meeting_augment dataset, there is an error:
<details>
<summary>train.log</summary>

```shell
# asr_train.py --config conf/tuning/train_transformer.yaml --ngpu 3 --backend pytorch --outdir exp/mdm_train_pytorch_tag.for.model/results --tensorboard-dir tensorboard/mdm_train_pytorch_tag.for.model --debugmode 1 --dict data/lang_1char/mdm_train_units.txt --debugdir exp/mdm_train_pytorch_tag.for.model --minibatches 0 --verbose 0 --resume --asr-model exp/mdm_train_pytorch_tag.for.model/results/model.acc.best --train-sample-rate 0.2 --rotate true --seed 1 --train-json ../../../../data/augment_data/m50.real.augment/train.json --valid-json ../../../../data/augment_data/m50.real.augment/dev.json 
# Started at Wed May  5 22:22:08 EDT 2021
#
/work/wj/DNC/venv/lib/python3.7/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
2021-05-05 22:22:09,421 (asr_train:322) WARNING: Skip DEBUG/INFO messages
None
Traceback (most recent call last):
  File "/work/wj/DNC/espnet/egs/ami/dnc1/../../../espnet/bin/asr_train.py", line 386, in <module>
    main(sys.argv[1:])
  File "/work/wj/DNC/espnet/egs/ami/dnc1/../../../espnet/bin/asr_train.py", line 374, in main
    train(args)
  File "/work/wj/DNC/espnet/espnet/asr/pytorch_backend/asr.py", line 333, in train
    model = model_class(idim, odim, args, asr_model=asr_model, mt_model=mt_model)
TypeError: __init__() got an unexpected keyword argument 'asr_model'
# Accounting: time=2 threads=1
# Ended (code 1) at Wed May  5 22:22:10 EDT 2021, elapsed time 2 seconds
```
</details>

What steps have I made wrong?
Thank you very much！

**Comment by Mintcat10** [comment]
> Hi，
> I tried to replicate the experiment，and follow yours step to train a DNC Transformer with the same configuration. The result of spectral cluster DER is the same，but the results of DNC are inconsistent. The DER of DNC is 32.52%，by contrast, the result of paper is 13.90%
> My shell cmds are follow:
> 
> run.sh
> ```shell
> #current path is DNC/
> dnc_root=espnet/egs/ami/dnc1
> path_to_datadir=data/augment_data
> m50_real_augment_path=$path_to_datadir/m50.real.augment
> m50_meeting_augment_path=$path_to_datadir/m50.meeting.augment
> dvecdict_meeting_path=$path_to_datadir/dvecdict.meeting.split100
> m50_real_path=$path_to_datadir/m50.real
> SC_scoring_path=scoring/sys_rttm/SC_result
> DNC_scoring_path=scoring/sys_rttm/DNC_result
> data_path=data	
> model_init=exp/mdm_train_pytorch_tag.for.model/results/model.acc.best
> resume_path=exp/mdm_train_pytorch_tag.for.model/results/snapshot.ep.50
> 
> ./path.sh
> ln -s $dnc_root dnc1
> #To generate training and validation data with sub-meeting length 50 and 1000 random shifts
> python3 datapreperation/gen_augment_data.py --input-scps data/train.scp --input-mlfs data/train.mlf \
> 	--filtEncomp --maxlen 50 --augment 1000 --varnormalise $m50_real_augment_path
> python3 datapreperation/gen_augment_data.py --input-scps data/dev.scp --input-mlfs data/dev.mlf \
> 	--filtEncomp --maxlen 50 --augment 1000 --varnormalise $m50_real_augment_path
> 	
> #To generate training data with sub-meeting length 50 and 1000 random shifts using the meeting randomisation
> python3 datapreperation/gen_dvecdict.py --input-scps data/train.scp --input-mlfs data/train.mlf \
> 	--filtEncomp --segLenConstraint 100 --meetingLevelDict $dvecdict_meeting_path
> 	
> python3 datapreperation/gen_augment_data.py --input-scps data/train.scp --input-mlfs data/train.mlf \
> 	--filtEncomp --maxlen 50 --augment 100 --varnormalise --randomspeaker  \
> 	--dvectordict $dvecdict_meeting_path/train.npz $m50_meeting_augment_path
> 	
> #To generate evaluation data
> python3 datapreperation/gen_augment_data.py --input-scps data/eval.scp --input-mlfs data/eval.mlf \
> 	--filtEncomp --maxlen 50 --varnormalise $m50_real_path
> 	
> cd $dnc_root
> 
> #To start training, run
> CUDA_VISIBLE_DEVICES=1,2,3 ./run.sh --stage 4 --stop_stage 4 --train_json ../../../../$m50_real_augment_path/train.json \
> 	--ngpu 3 --dev_json ../../../../$m50_real_augment_path/dev.json --tag tag.for.model
> 
> #To track the progress of the training, run
> tail -f exp/mdm_train_pytorch_tag.for.model/train.log
> 
> #Decode a DNC Tranformer
> #Similar to the command used for training, run
> #The decoding results are, by default, stored in multiple json files in exp/mdm_train_pytorch_tag.for.model/decode_dev_xxxxx/data.JOB.json
> ./run.sh --stage 5 --decode_json ../../../../$m50_real_path/eval.json --tag tag.for.model
> 
> cd ../../../../
> #Running spectral clustering
> #To run spectral clustering on previously generated evalutation data, for example for sub-meeting lengths 50:
> python3 scoring/run_spectralclustering.py --p-percentile 0.95 --custom-dist cosine \
> 	--json-out $SC_scoring_path/eval95k24.1.json  $m50_real_path/eval.json
> #Evaluation of clustering results
> #First the DNC or SC output has to be converted into the RTTM format: 
> #For SC:
> python3 scoring/gen_rttm.py --input-scp $data_path/eval.scp --js-dir $SC_scoring_path \
> 	--js-num 1 --js-name eval95k24 --rttm-name eval95k24
> #To score the result the reference rttm has to first be split into the appropriate sub-meeting lengths:
> python3 scoring/split_rttm.py --submeeting-rttm $SC_scoring_path/eval95k24.rttm \
> 	--input-rttm scoring/refoutputeval.rttm --output-rttm $SC_scoring_path/reference.rttm
> #Finally, the speaker error rate has to be calculated using:
> python3 scoring/score_rttm.py --score-rttm $SC_scoring_path/eval95k24.rttm \
> 	--ref-rttm $SC_scoring_path/reference.rttm --output-scoredir $SC_scoring_path/result
> 
> 
> #For DNC:
> \cp $dnc_root/exp/mdm_train_pytorch_tag.for.model/decode_mdm_dev_decode/data* $DNC_scoring_path
> python3 scoring/gen_rttm.py --input-scp $data_path/eval.scp --js-dir $DNC_scoring_path \
> 	--js-num 16 --js-name data --rttm-name evaldnc
> #To score the result the reference rttm has to first be split into the appropriate sub-meeting lengths:
> python3 scoring/split_rttm.py --submeeting-rttm $DNC_scoring_path/evaldnc.rttm \
> 	--input-rttm scoring/refoutputeval.rttm --output-rttm $DNC_scoring_path/reference.rttm
> #Finally, the speaker error rate has to be calculated using:
> python3 scoring/score_rttm.py --score-rttm $DNC_scoring_path/evaldnc.rttm \
> 	--ref-rttm $DNC_scoring_path/reference.rttm --output-scoredir $DNC_scoring_path/result
> ```
> 
> I consider the problem is that the training dataset was augmented by three ways, while I only used m50_real_augment dataset to train model.
> Then I want to add parameter --init_model $model_init to train m50_meeting_augment dataset, there is an error:
> 
> train.log
> ```shell
> # asr_train.py --config conf/tuning/train_transformer.yaml --ngpu 3 --backend pytorch --outdir exp/mdm_train_pytorch_tag.for.model/results --tensorboard-dir tensorboard/mdm_train_pytorch_tag.for.model --debugmode 1 --dict data/lang_1char/mdm_train_units.txt --debugdir exp/mdm_train_pytorch_tag.for.model --minibatches 0 --verbose 0 --resume --asr-model exp/mdm_train_pytorch_tag.for.model/results/model.acc.best --train-sample-rate 0.2 --rotate true --seed 1 --train-json ../../../../data/augment_data/m50.real.augment/train.json --valid-json ../../../../data/augment_data/m50.real.augment/dev.json 
> # Started at Wed May  5 22:22:08 EDT 2021
> #
> /work/wj/DNC/venv/lib/python3.7/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
>   warnings.warn(warning.format(ret))
> 2021-05-05 22:22:09,421 (asr_train:322) WARNING: Skip DEBUG/INFO messages
> None
> Traceback (most recent call last):
>   File "/work/wj/DNC/espnet/egs/ami/dnc1/../../../espnet/bin/asr_train.py", line 386, in <module>
>     main(sys.argv[1:])
>   File "/work/wj/DNC/espnet/egs/ami/dnc1/../../../espnet/bin/asr_train.py", line 374, in main
>     train(args)
>   File "/work/wj/DNC/espnet/espnet/asr/pytorch_backend/asr.py", line 333, in train
>     model = model_class(idim, odim, args, asr_model=asr_model, mt_model=mt_model)
> TypeError: __init__() got an unexpected keyword argument 'asr_model'
> # Accounting: time=2 threads=1
> # Ended (code 1) at Wed May  5 22:22:10 EDT 2021, elapsed time 2 seconds
> ```
> 
> What steps have I made wrong?
> Thank you very much！

Hi, I have the same question. Did you get better result?

**Comment by qiujiali** [comment]
The latest commit (978c588) should address the error when loading a pre-trained model. My apologies for the bug. We will look into the performance issue and update you soon.

**Comment by qiujiali** [comment]
Thank you for your patience. Please see the latest commit (f5fc54f) for updated configurations and detailed instructions on how to reproduce the final results here https://github.com/qiujiali/espnet/blob/dnc/egs/ami/dnc1/README.md.
